name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build
      env:
        GOOGLE_AI_API_KEY: ${{ secrets.GOOGLE_AI_API_KEY }}
        NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/fusefoundry
          
          # Backup current version
          sudo -u fusefoundry cp -r .next .next.backup.$(date +%Y%m%d_%H%M%S) || true
          
          # Pull latest changes
          sudo -u fusefoundry git fetch origin
          sudo -u fusefoundry git reset --hard origin/main
          
          # Install dependencies
          sudo -u fusefoundry npm ci --production=false
          
          # Build application
          sudo -u fusefoundry npm run build
          
          # Restart application
          sudo -u fusefoundry pm2 restart fusefoundry
          
          # Clean up old backups (keep last 5)
          sudo -u fusefoundry find /var/www/fusefoundry -name ".next.backup.*" -type d | sort -r | tail -n +6 | xargs rm -rf
          
          echo "✅ Deployment completed successfully!"

    - name: Health Check
      run: |
        sleep 10
        curl -f ${{ secrets.NEXT_PUBLIC_SITE_URL }}/api/health || exit 1
      continue-on-error: false
